global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'authentification'
    static_configs:
      - targets: ['host.docker.internal:8010']
        labels:
          service: 'authentification'
  - job_name: 'bdd'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          service: 'bdd'
  - job_name: 'ia'
    static_configs:
      - targets: ['host.docker.internal:8001']
        labels:
          service: 'ia'
  - job_name: 'payment'
    static_configs:
      - targets: ['host.docker.internal:8015']
        labels:
          service: 'payment'
  - job_name: 'notification'
    static_configs:
      - targets: ['host.docker.internal:8016']
        labels:
          service: 'notification'
